default_language_version:
    python: python3.10.11
default_stages: [pre-commit, pre-push]
minimum_pre_commit_version: 3.2.2

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy

-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
